# DL4 - 卷积神经网络（CNN）基础实验

本 notebook 按实验任务代号整理代码部分，便于直接运行与记录结果。

## 环境准备

In [1]:
import torch
from torch import nn

torch.manual_seed(42)
print(torch.__version__)

2.10.0


## 实验1.2：用代码实现二维卷积

In [2]:
def corr2d(X, K):
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
    return Y

X = torch.tensor([
    [0., 1., 2.],
    [3., 4., 5.],
    [6., 7., 8.]
])

K = torch.tensor([
    [0., 1.],
    [2., 3.]
])

Y = corr2d(X, K)
print('输入 X =\n', X)
print('卷积核 K =\n', K)
print('卷积输出 Y =\n', Y)

输入 X =
 tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
卷积核 K =
 tensor([[0., 1.],
        [2., 3.]])
卷积输出 Y =
 tensor([[19., 25.],
        [37., 43.]])


In [3]:
# 修改输入矩阵和卷积核，观察输出变化
X2 = torch.tensor([
    [1., 2., 3., 4.],
    [5., 6., 7., 8.],
    [9., 10., 11., 12.],
    [13., 14., 15., 16.]
])

K2 = torch.tensor([
    [1., 0.],
    [0., -1.]
])

print('新的输入 X2 =\n', X2)
print('新的卷积核 K2 =\n', K2)
print('新的输出 Y2 =\n', corr2d(X2, K2))

新的输入 X2 =
 tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
新的卷积核 K2 =
 tensor([[ 1.,  0.],
        [ 0., -1.]])
新的输出 Y2 =
 tensor([[-5., -5., -5.],
        [-5., -5., -5.],
        [-5., -5., -5.]])


In [4]:
# 尝试一个简单的边缘检测核
X_edge = torch.tensor([
    [1., 1., 1., 0., 0., 0.],
    [1., 1., 1., 0., 0., 0.],
    [1., 1., 1., 0., 0., 0.],
    [1., 1., 1., 0., 0., 0.]
])

K_edge = torch.tensor([[1., -1.]])
Y_edge = corr2d(X_edge, K_edge)

print('边缘检测输入 =\n', X_edge)
print('边缘检测卷积核 =\n', K_edge)
print('边缘检测输出 =\n', Y_edge)

边缘检测输入 =
 tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])
边缘检测卷积核 =
 tensor([[ 1., -1.]])
边缘检测输出 =
 tensor([[0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.]])


## 实验1.3：Padding 对输出尺寸的影响

In [5]:
X = torch.rand(size=(1, 1, 8, 8))
padding_list = [0, 1, 2]

for padding in padding_list:
    conv2d = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, padding=padding, stride=1)
    Y = conv2d(X)
    print(f'padding={padding}, 输出尺寸={tuple(Y.shape)}')

padding=0, 输出尺寸=(1, 1, 6, 6)
padding=1, 输出尺寸=(1, 1, 8, 8)
padding=2, 输出尺寸=(1, 1, 10, 10)


In [6]:
# 按报告表格形式展示结果
X = torch.rand(size=(1, 1, 8, 8))
print('kernel_size | padding | stride | 输入尺寸 | 输出尺寸')
for padding in [0, 1, 2]:
    conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=padding, stride=1)
    Y = conv2d(X)
    print(f'3 | {padding} | 1 | 8x8 | {Y.shape[-2]}x{Y.shape[-1]}')

kernel_size | padding | stride | 输入尺寸 | 输出尺寸
3 | 0 | 1 | 8x8 | 6x6
3 | 1 | 1 | 8x8 | 8x8
3 | 2 | 1 | 8x8 | 10x10


## 实验1.4：Stride 对输出尺寸与信息压缩的影响

In [7]:
X = torch.rand(size=(1, 1, 8, 8))
stride_list = [1, 2, 3]

for stride in stride_list:
    conv2d = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, padding=1, stride=stride)
    Y = conv2d(X)
    print(f'stride={stride}, 输出尺寸={tuple(Y.shape)}')

stride=1, 输出尺寸=(1, 1, 8, 8)
stride=2, 输出尺寸=(1, 1, 4, 4)
stride=3, 输出尺寸=(1, 1, 3, 3)


In [8]:
# 按报告表格形式展示结果
X = torch.rand(size=(1, 1, 8, 8))
print('kernel_size | padding | stride | 输入尺寸 | 输出尺寸')
for stride in [1, 2, 3]:
    conv2d = nn.Conv2d(1, 1, kernel_size=3, padding=1, stride=stride)
    Y = conv2d(X)
    print(f'3 | 1 | {stride} | 8x8 | {Y.shape[-2]}x{Y.shape[-1]}')

kernel_size | padding | stride | 输入尺寸 | 输出尺寸
3 | 1 | 1 | 8x8 | 8x8
3 | 1 | 2 | 8x8 | 4x4
3 | 1 | 3 | 8x8 | 3x3


## 实验2.1：多输入通道卷积

In [9]:
def corr2d_multi_in(X, K):
    return sum(corr2d(x, k) for x, k in zip(X, K))

X = torch.arange(18, dtype=torch.float32).reshape(2, 3, 3)
K = torch.ones((2, 2, 2))
Y = corr2d_multi_in(X, K)

print('输入 X 的形状:', X.shape)
print('卷积核 K 的形状:', K.shape)
print('输出 Y 的形状:', Y.shape)
print('输出 Y =\n', Y)

输入 X 的形状: torch.Size([2, 3, 3])
卷积核 K 的形状: torch.Size([2, 2, 2])
输出 Y 的形状: torch.Size([2, 2])
输出 Y =
 tensor([[52., 60.],
        [76., 84.]])


In [10]:
# 手动解释左上角一个输出元素如何得到
window_ch1 = X[0, 0:2, 0:2]
window_ch2 = X[1, 0:2, 0:2]
kernel_ch1 = K[0]
kernel_ch2 = K[1]
result = (window_ch1 * kernel_ch1).sum() + (window_ch2 * kernel_ch2).sum()

print('通道1局部窗口 =\n', window_ch1)
print('通道2局部窗口 =\n', window_ch2)
print('对应输出左上角元素 =', result.item())

通道1局部窗口 =
 tensor([[0., 1.],
        [3., 4.]])
通道2局部窗口 =
 tensor([[ 9., 10.],
        [12., 13.]])
对应输出左上角元素 = 52.0


## 实验2.2：多输出通道卷积

In [11]:
X = torch.rand(1, 3, 8, 8)
conv2d = nn.Conv2d(in_channels=3, out_channels=4, kernel_size=3, padding=1)
Y = conv2d(X)

print('输入形状:', X.shape)
print('输出形状:', Y.shape)

输入形状: torch.Size([1, 3, 8, 8])
输出形状: torch.Size([1, 4, 8, 8])


In [12]:
# 计算参数量
weight_params = conv2d.weight.numel()
bias_params = conv2d.bias.numel()
total_params = weight_params + bias_params

print('权重张量形状:', tuple(conv2d.weight.shape))
print('权重参数量:', weight_params)
print('偏置参数量:', bias_params)
print('总参数量:', total_params)

# 理论计算：out_channels * (in_channels * kernel_h * kernel_w + 1)
theory_params = 4 * (3 * 3 * 3 + 1)
print('理论参数量:', theory_params)

权重张量形状: (4, 3, 3, 3)
权重参数量: 108
偏置参数量: 4
总参数量: 112
理论参数量: 112


## 实验2.3：池化层原理与对比实验

In [13]:
X = torch.tensor([[[[1., 2., 3., 4.],
                     [5., 6., 7., 8.],
                     [9., 10., 11., 12.],
                     [13., 14., 15., 16.]]]])

max_pool = nn.MaxPool2d(kernel_size=2, stride=2)
avg_pool = nn.AvgPool2d(kernel_size=2, stride=2)

Y_max = max_pool(X)
Y_avg = avg_pool(X)

print('输入 X =\n', X)
print('最大池化结果 =\n', Y_max)
print('平均池化结果 =\n', Y_avg)

输入 X =
 tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])
最大池化结果 =
 tensor([[[[ 6.,  8.],
          [14., 16.]]]])
平均池化结果 =
 tensor([[[[ 3.5000,  5.5000],
          [11.5000, 13.5000]]]])


In [14]:
# 观察池化后尺寸变化
print('输入尺寸:', tuple(X.shape))
print('最大池化后尺寸:', tuple(Y_max.shape))
print('平均池化后尺寸:', tuple(Y_avg.shape))

输入尺寸: (1, 1, 4, 4)
最大池化后尺寸: (1, 1, 2, 2)
平均池化后尺寸: (1, 1, 2, 2)
